config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :rooftops, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rooftop.rb
class Rooftop < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  validates :name, :description, :address, presence: true
  monetize :price_cents, numericality: { greater_than_or_equal_to: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_rooftops, foreign_key: :owner_id,
                            class_name: 'Rooftop',
                            dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/rooftops_controller.rb
class RooftopsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_rooftop, only: :show

  def index
    @rooftops = Rooftop.all
  end

  def show
  end

  def new
    @rooftop = Rooftop.new
  end

  def create
    @rooftop = Rooftop.new(rooftop_params)
    @rooftop.owner = current_user

    if @rooftop.save
      redirect_to rooftop_path(@rooftop)
    else
      render :new
    end
  end

  private

  def set_rooftop
    @rooftop = Rooftop.find(params[:id])
  end

  def rooftop_params
    params.require(:rooftop).permit(:name, :description, :price, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? yield(:title) : Rooftop %></title>
    <%= favicon_link_tag asset_path('logo_green.png') %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="https://kit.fontawesome.com/b4e5ca6111.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <% if controller.controller_name == "pages" && controller.action_name == "home" %>
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0)), url('https://a0.muscache.com/4ea/air/v2/pictures/41d7e198-fcfc-41d5-8735-3fe64c358d90.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90');">
        <%= render "shared/navbar" %>
        <div class="container homepage">
          <h1>Rent a rooftop, terrace or patio anywhere</h1>
          <p><span id="banner-typed-text"></span></p>
          <%= link_to "Find a rooftop!", rooftops_path, {class: "btn btn-primary"} %>
        </div>
      </div>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>
    <%= yield %>
    <%#= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/rooftops/_form.html.erb
<%= simple_form_for(@rooftop) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :price %>

    <div>
      <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', :back, class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/rooftops/_rooftop.html.erb
<div class="col-sm-4">
<%= link_to rooftop_path(rooftop), {class: "show-link"} do %>
  <div class="card-rooftop">
    <%= image_tag("apt_0") %>
    <!-- <img src="https://i.pinimg.com/564x/dd/0c/d8/dd0cd869ad5759359202d7066bb67276.jpg" /> -->
    <!-- <img src="https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80" /> -->
    <div class="card-rooftop-infos">
      <div>
        <h2><%= rooftop.name %></h2>
        <p><%= rooftop.description %></p>
      </div>
      <h2 class="card-rooftop-pricing"><%= rooftop.price %>€</h2>
      <img src="https://avatars2.githubusercontent.com/u/54022229?v=4" class="card-rooftop-user avatar-bordered" />
    </div>
  </div>
<% end %>
</div>

app/views/rooftops/index.html.erb
<% content_for(:title) do %>
  All rooftops
<% end %>

<div class="container">
  <div class="row rooftop-cards">
    <%= render @rooftops  %>
    <%# @rooftops.each do |r| %>
      <!-- <div class="col-sm-4"> -->
        <%#= render "card", rooftop: r %>
      <!-- </div> -->
    <%# end %>
  </div>
</div>

app/views/rooftops/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0)), url(https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80);">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="form-login">
          <h2>List your rooftop!</h2>
            <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooftops/show.html.erb
<% content_for(:title) do %>
  <%= @rooftop.name %>
<% end %>

<div class="show-header">
  <ul id="grid">
    <li id="main"><%=image_tag("apt_0")%></li>
    <li><%=image_tag("apt_1")%></li>
    <li><%=image_tag("apt_2")%></li>
    <li id="secondary"><%=image_tag("apt_3")%></li>
    <li><%=image_tag("apt_4")%></li>
  </ul>
  <div class="btn-group-social">
    <a href="#" class="btn btn-social share"><i class="far fa-share-square"></i>  Share</a>
    <a href="#" class="btn btn-social save"><i class="far fa-heart"></i>  Save</a>
  </div>
  <a href="#" class="btn btn-social photos">See photos</a>
</div>

<div class="show-container">
  <div class="apt-info">
    <div class="apt-header">
      <div class="apt-title">
        <h1><%= @rooftop.name %></h1>
        <p><%= @rooftop.address %></p>
      </div>
      <div class="owner">
        <img src="https://avatars2.githubusercontent.com/u/54022229?v=4" alt="" class="show-avatar">
        <p>Fanny</p>
      </div>
    </div>
    <div class="apt-details">
      <div class="apt-summary">
        <p>4 guests</p>
        <p>House</p>
        <p>2 beds</p>
        <p>1 bathroom</p>
      </div>
      <hr>
      <div class="details">
        <h3><i class="fas fa-home"></i>  Entire home</h3>
        <p>You’ll have the apartment to yourself.</p>
        <h3><i class="fas fa-hand-sparkles"></i>  Self check-in</h3>
        <p>Check yourself in with the lockbox.</p>
        <h3><i class="fas fa-lock"></i>  Sparkling clean</h3>
        <p>12 recent guests said this place was sparkling clean.</p>
      </div>
    </div>
    <hr>
    <div class="apt-description">
      <p><%= @rooftop.description %></p>
    </div>
    <hr>
    <div class="apt-amenities">
      <p>Amenities</p>
      <ul class="amenities">
        <div class="amenities-1">
          <li><i class="fas fa-wifi"></i> Wifi</li>
          <li><i class="fas fa-utensils"></i> Kitchen</li>
          <li><i class="fas fa-mug-hot"></i> Coffee Machine</li>
        </div>
        <div class="amenities-2">
          <li><i class="fas fa-blender"></i> Blender</li>
          <li><i class="fas fa-fan"></i> Air conditionning</li>
          <li><i class="fas fa-wind"></i> Carbon Dioxide detector</li>
        </div>
      </ul>
    </div>
    <%= link_to "Delete", rooftop_path(@rooftop),
        method: :delete,
        class: "btn btn-secondary",
        data: { confirm: "Are you sure?" } %>
  </div>
  <div class="apt-booking">
    <div><span class="price"><s><%= (@rooftop.price * 1.20).round %>€</s><strong> <%= @rooftop.price.round %>€ </strong></span><span class="text-small">/night</span></div>
    <div><i class="fas fa-star"></i> <span class="text-small">4,75</span> <span class="text-small light-text">(620 evaluaciones)</span></div>
    <hr>

    <div class="select">
      <div class="text-small">Dates</div>
      <div class="selector light-text">20/04/2020 > 21/4/2020</div>
        <div class="text-small">Guests</div>
        <div class="selector light-text">2 guests   <i class="fas fa-caret-down"></i></div>
    </div>

    <div class="price_recap light-text">
        <div>32€ x 1 noche <i class="far fa-question-circle"></i></div>
        <div>32€</div>
    </div>
    <hr>

    <div class="price_recap light-text">
        <div>Gastos de limpieza <i class="far fa-question-circle"></i></div>
        <div>20</div>
    </div>
    <hr>

    <div class="price_recap light-text">
        <div>Tarifia de servicio <i class="far fa-question-circle"></i></div>
        <div>9€</div>
    </div>
    <hr>

    <div class="price_recap">
        <div>Total</div>
        <div>32€</div>
    </div>
    <button>Make Booking</button>

    <div class="disclaimer">
      <p>You won’t be charged yet.</p>
      <p>Certain reservations may also require a security deposit.</p>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if controller.controller_name == "pages" && controller.action_name == "home" %>
  <div class="navbar navbar-expand-sm navbar-lewagon navbar-fixed-top transparent">
      <%= link_to root_path, class: "navbar-brand" do %>
        <p id="logo-white"><i class="fas fa-triangle"></i> rooftop</p>
      <% end %>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-fixed-top">
    <%= link_to root_path, class: "navbar-brand" do %>
      <p id="logo-green"><i class="fas fa-triangle"></i> rooftop</p>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "See all rooftops", rooftops_path, class: "btn btn-primary mr-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rent a rooftop", new_rooftop_path, class: "btn btn-ghost mr-3" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My Dashboard", "#", class: "dropdown-item" %>
              <%= link_to "See all rooftops", rooftops_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>